### ISSUE TITLE
AutoRetainer 3.0.0.0 Checklist

### ISSUE THREAD

**Issue by kawaii** [PunishXIV/AutoRetainer#9]
- [ ] Task based system for retainer ventures, supporting individually assigned venture types, "Entrust Duplicates" inventory management, and various Gil withdrawal/deposit operations
  - [ ] Venture selection drop down menu consisting of 4 options; `Disabled`, `Quick Venture (1H)`, `Expedition (18H)`, `Hunting/Gathering`
  - [ ] When the venture type is `Expedition (18H)` or `Hunting/Gathering` display an additional drop down to specify the exact venture desired
- [ ] Plugin should no longer prevent manual interference or use of menus while idling for the next task. If any sub-menus are open however the plugin will cease to operate until back at the main Summoning Bell UI
- [ ] Check for closer housing ward Summoning Bell (within 3y) before locking on to the closest door when using the housing bells option (may need LoS check)
- [ ] Delete button added to character config UI window for removing config (i.e. logged into friends account and now their retainers show up in your UI)
